### ISSUE TITLE
Whitespace removed when formatting

### ISSUE THREAD

**Issue by onceatime** [mblode/vscode-twig-language#12]
```
{% for value in ['foo', 'bar', 'baz'] %}
```

becomes (whitespace removed between for and Array)

```
{% for value in['foo', 'bar', 'baz'] %}
```

this way twig compiler emits an error.

**Comment by mblode** [comment]
Hey @onceatime , I have just pushed an update to Twig Language 2 with a brand new formatter using Prettydiff 3 which brings about some major bug fixes. This bug has now been fixed in the newest version of the extension. Sorry about the slow development speeds and sub-par communication but hopefully these updates have fixed some of your other problems.

**Comment by mblode** [comment]
0.10.0 preserves Twig expression contents and adds whitespace regression tests.
