### ISSUE TITLE
Auto-changes on save - image

### ISSUE THREAD

**Issue by GlynL** [mblode/vscode-twig-language#14]
When saving the file the following is automatically changed.
From this:
style='background-image: url({{post.thumbnail.src('medium'}})'

To this:
style='background-image: url({{post.thumbnail.src(' medium')}})'="medium')}})'"

**Comment by mblode** [comment]
Hi @GlynL, you have run into a really annoying known glitch in the formatting system I'm using called PrettyDiff. Luckily, the developer is tirelessly working on a new version which should hopefully fix this issue. I will let you know if we get a fix for this 👍

**Comment by mblode** [comment]
Hey @GlynL, I have just pushed an update to Twig Language 2 with a brand new formatter using Prettydiff 3 which brings about some major bug fixes. This bug has now been fixed in the newest version of the extension. Sorry about the slow development speeds and sub-par communication but hopefully these updates have fixed some of your other problems.

**Comment by mblode** [comment]
0.10.0 is out with a new formatter. Please share the source as text if this still happens; the screenshot wasn’t enough to confirm it.
