### ISSUE TITLE
No twig language installed

### ISSUE THREAD

**Issue by soniktrooth** [mblode/vscode-twig-language#7]
I uninstalled https://github.com/whatwedo/vscode-twig and installed your plugin but now I don't have a Twig language to associate with files. I've tried uninstalling and reinstalling but nothing seems to work. Reinstalling https://github.com/whatwedo/vscode-twig brings it back but then I don't have the snippets that I want from your plugin. Am I missing something?

**Comment by mblode** [comment]
Hey @soniktrooth,
Last week based on feedback from some users, I changed the extension so that there is no longer a "TWIG" language but rather .html files are recognised as TWIG. The benefit of this, as opposed to other extensions, is that .html files automatically include intellisense and emmet shortcuts. So you don't need to do anything except open up a .twig.html/.html/.twig file and it should include snippets, formatting, hover, and syntax highlighting for TWIG.
I hope this helps :)

**Comment by dzpt** [comment]
@mblode you should have twig language option to use another extension.
For example im using jinja2 with j2 extension.
I have to change all files to twig to get recogination.

**Comment by mblode** [comment]
Twig Language still uses HTML mode in 0.10.0. For a dedicated Twig language mode, use Twig Language 2; both share the formatter.
